# Generated by Django 5.1.2 on 2024-12-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_module_registration_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.AddField(
            model_name='module',
            name='registered_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='register',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itreporting.module'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registerdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
